PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS companies (id TEXT PRIMARY KEY,company_id TEXT UNIQUE NOT NULL,company_name TEXT NOT NULL,email TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',deposit_balance REAL NOT NULL DEFAULT 0,locked_balance REAL NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,role TEXT NOT NULL,company_id TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',full_name TEXT,phone TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_login_at TEXT,FOREIGN KEY(company_id) REFERENCES companies(company_id));
CREATE TABLE IF NOT EXISTS company_users (id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE,company_id TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'company_admin',is_primary_company_account INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(company_id) REFERENCES companies(company_id));
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY,company_id TEXT NOT NULL,report_code TEXT UNIQUE,reporter_code TEXT UNIQUE,title TEXT,category TEXT,violation_type TEXT,estimated_loss REAL NOT NULL DEFAULT 0,description TEXT,incident_date TEXT,location TEXT,status TEXT NOT NULL DEFAULT 'baru',reward_amount REAL NOT NULL DEFAULT 0,reward_min_amount REAL NOT NULL DEFAULT 0,reward_claim_status TEXT NOT NULL DEFAULT 'none',reward_claimed INTEGER NOT NULL DEFAULT 0,payout_wallet TEXT,evidence_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(company_id) REFERENCES companies(company_id));
CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY,user_id TEXT,company_id TEXT,type TEXT NOT NULL,amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending',method TEXT,tx_hash TEXT,report_id TEXT,metadata_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,processed_at TEXT);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY,actor_user_id TEXT,actor_email TEXT,actor_role TEXT,company_id TEXT,action TEXT NOT NULL,entity_type TEXT,entity_id TEXT,metadata_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_users_company ON users(company_id); CREATE INDEX IF NOT EXISTS idx_company_users_company ON company_users(company_id); CREATE INDEX IF NOT EXISTS idx_reports_company ON reports(company_id); CREATE INDEX IF NOT EXISTS idx_transactions_company ON transactions(company_id); CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);
